r"""V039-R2-002：Android 打包脚本必须让 APK 带上真实版本号（离线）。

真机现场（`evidence/mobile-20260910/result.json`，台账 V039-R2-002）：按
`desktop/scripts/build-android.ps1` 产出的 APK 装机为 `versionCode=1 /
versionName=1.0`，而设备上已有 `tauri android build` 产的同包名应用
（`versionCode=3007`），`adb install -r` 直接以 `INSTALL_FAILED_VERSION_DOWNGRADE`
失败，这次测试只能改用 `-d` 允许降级安装。根因：`gen/android/app/build.gradle.kts`
的 `versionCode = tauriProperties.getProperty("tauri.android.versionCode", "1")`
从 `app/tauri.properties` 取值，缺省 `1` / `1.0`；该文件由 tauri CLI 生成，
而本脚本只跑 `cargo build --lib` 与 `gradlew :app:assembleArm64Debug`。

本文件全程离线，不构建 APK、不调用 cargo / npm / gradle 本体、不写真实
`gen/android/` 产物，验证分三层：

1. **静态**：脚本在 PowerShell 5.1 自己的解析器下 0 语法错误，并满足仓库既有
   约定（无 BOM 时必须纯 ASCII、LF 行尾，见 V039-R1-001）。
2. **dry-run**：真实脚本与真实 `tauri.conf.json` 复制进 `tempfile` 沙箱，
   `JAVA_HOME` / `NDK_HOME` / `ANDROID_HOME` 指向沙箱里的占位文件，`npm` /
   `cargo` / `gradlew.bat` 换成只留调用痕迹的替身（与
   `test_v039_r1_reset_script.py` 同法）。沙箱里的 `gradlew.bat` 会把「打包
   那一刻的 `app/tauri.properties`」抄一份，用来证明属性文件在 gradle 之前
   写完且内容可用。
3. **版本号语义**：与 tauri CLI 2.11.4 同一条派生式
   `major * 1000000 + minor * 1000 + patch`（`config.schema.json` 的
   `bundle > android > versionCode` 与 CLI 源码一致），所以 0.3.7 → 3007
   与真机现存包同号，当前版本必定大于它，覆盖安装不再降级。
"""

from __future__ import annotations

import json
import os
import shutil
import sys
import subprocess
import tempfile
from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path

import pytest


def _ps_output_encoding() -> str:
    """PowerShell 5.1 管道输出跟随系统 ANSI 代码页；按其解码，跨编码环境不崩。"""
    return "mbcs" if sys.platform == "win32" else "utf-8"

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT_PATH = REPO_ROOT / "desktop" / "scripts" / "build-android.ps1"
TAURI_CONF_PATH = REPO_ROOT / "desktop" / "src-tauri" / "tauri.conf.json"
GRADLE_APP_BUILD = (
    REPO_ROOT / "desktop" / "src-tauri" / "gen" / "android" / "app" / "build.gradle.kts"
)
POWERSHELL = shutil.which("powershell.exe")

# tauri CLI 写出的 `app/tauri.properties` 固定带这行头注释（本文件只断言键值，头注释一并核对）。
PROPERTIES_HEADER = "// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY."
# 真机现存包的版本号：0.3.7 的 `tauri android build` 产物（台账 V039-R2-002）。
DEVICE_VERSION_CODE = 3007

# 构造沙箱时用它表示「保留真实 tauri.conf.json 的 version 原样」。
_KEEP = object()


def _require_powershell() -> str:
    if not POWERSHELL:
        pytest.fail("Windows PowerShell 5.1 (powershell.exe) is unavailable on this machine.")
    return POWERSHELL


def _version_code(version: str) -> int:
    """tauri CLI 对 0.3.9 这类版本的派生式；预发布后缀按 semver 语义忽略。"""
    major, minor, patch = (int(part) for part in version.split("-", 1)[0].split("+", 1)[0].split("."))
    return major * 1_000_000 + minor * 1_000 + patch


def _properties_lines(properties: Path) -> dict[str, str]:
    lines = properties.read_text(encoding="ascii").splitlines()
    assert lines[0] == PROPERTIES_HEADER, lines
    return dict(line.split("=", 1) for line in lines[1:])


class _AndroidBuildSandbox:
    """隔离的打包沙箱：临时 desktop 布局 + 占位工具链 + 替身命令。"""

    def __init__(self, version: object = _KEEP) -> None:
        self.root = Path(tempfile.mkdtemp(prefix="v039_r2_android_"))
        self.desktop = self.root / "desktop"
        self.tauri_root = self.desktop / "src-tauri"
        self.android_root = self.tauri_root / "gen" / "android"
        self.app_dir = self.android_root / "app"
        self.bin_dir = self.root / "bin"
        self.scripts = self.desktop / "scripts"
        for path in (self.scripts, self.tauri_root, self.app_dir, self.bin_dir):
            path.mkdir(parents=True)

        self.script = self.scripts / SCRIPT_PATH.name
        shutil.copyfile(SCRIPT_PATH, self.script)

        config = json.loads(TAURI_CONF_PATH.read_text(encoding="utf-8"))
        if version is not _KEEP:
            if version is None:
                config.pop("version", None)
            else:
                config["version"] = version
        self.app_version = config.get("version")
        self.tauri_conf = self.tauri_root / "tauri.conf.json"
        self.tauri_conf.write_text(
            json.dumps(config, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )

        self.mobile_dist = self.desktop / "mobile" / "dist"
        self.mobile_dist.mkdir(parents=True)
        (self.mobile_dist / "index.html").write_text("<html>stub</html>\n", encoding="utf-8")

        self.calls = self.root / "calls.txt"
        self.properties = self.app_dir / "tauri.properties"
        self.properties_at_gradle_time = self.root / "properties-at-gradle-time.txt"
        self._write_toolchain()
        self._write_command_stubs()

    # -- 沙箱内容 --------------------------------------------------------------------

    @property
    def library(self) -> Path:
        return self.tauri_root / "target/aarch64-linux-android/debug/libhsr_partner_harness_lib.so"

    def _write_toolchain(self) -> None:
        """脚本只对工具链做存在性检查，空占位文件即可满足。"""
        self.java_home = self.root / "java"
        self.ndk_home = self.root / "ndk"
        self.android_home = self.root / "sdk"
        ndk_bin = self.ndk_home / "toolchains/llvm/prebuilt/windows-x86_64/bin"
        for placeholder in (
            self.java_home / "bin/java.exe",
            ndk_bin / "aarch64-linux-android24-clang.cmd",
            ndk_bin / "aarch64-linux-android24-clang++.cmd",
            ndk_bin / "llvm-ar.exe",
            self.android_home / "platforms/android-36/android.jar",
        ):
            placeholder.parent.mkdir(parents=True, exist_ok=True)
            placeholder.write_bytes(b"")

    def _write_stub(self, path: Path, lines: list[str]) -> None:
        """替身命令只留调用痕迹与必要的产物，不执行真实构建。"""
        path.write_text(
            "@echo off\r\n" + "\r\n".join(lines) + "\r\nexit /b 0\r\n",
            encoding="ascii",
            newline="\r\n",
        )

    def _write_command_stubs(self) -> None:
        record = f'>>"{self.calls}" echo '
        self._write_stub(self.bin_dir / "npm.cmd", [record + "npm %*"])
        self._write_stub(
            self.bin_dir / "cargo.cmd",
            [
                record + "cargo %*",
                f'md "{self.library.parent}" 2>nul',
                f'>"{self.library}" echo stub-library',
            ],
        )
        self._write_stub(
            self.android_root / "gradlew.bat",
            [
                record + "gradlew %*",
                f'if exist "{self.properties}" copy /y "{self.properties}" '
                f'"{self.properties_at_gradle_time}" >nul',
            ],
        )

    # -- 运行 ------------------------------------------------------------------------

    @property
    def env(self) -> dict[str, str]:
        return {
            **os.environ,
            "PATH": str(self.bin_dir) + os.pathsep + os.environ.get("PATH", ""),
            "JAVA_HOME": str(self.java_home),
            "NDK_HOME": str(self.ndk_home),
            "ANDROID_HOME": str(self.android_home),
            # 置空让脚本走它自己的 WRY 缺省值，结果不受宿主环境影响。
            "WRY_ANDROID_PACKAGE": "",
            "WRY_ANDROID_LIBRARY": "",
            "WRY_ANDROID_KOTLIN_FILES_OUT_DIR": "",
        }

    def run(self, *args: str, timeout: float = 120.0) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [
                _require_powershell(),
                "-NoProfile",
                "-ExecutionPolicy",
                "Bypass",
                "-File",
                str(self.script),
                *args,
            ],
            cwd=str(self.desktop),
            env=self.env,
            capture_output=True,
            text=False,
            encoding=_ps_output_encoding(),
            errors="replace",
            timeout=timeout,
        )

    def recorded_calls(self) -> list[str]:
        if not self.calls.exists():
            return []
        return [
            line.split(" ", 1)[0]
            for line in self.calls.read_text(encoding="ascii").splitlines()
            if line.strip()
        ]

    def cleanup(self) -> None:
        shutil.rmtree(self.root, ignore_errors=True)


@contextmanager
def _sandbox(version: object = _KEEP) -> Iterator[_AndroidBuildSandbox]:
    box = _AndroidBuildSandbox(version)
    try:
        yield box
    finally:
        box.cleanup()


@pytest.fixture
def sandbox() -> Iterator[_AndroidBuildSandbox]:
    with _sandbox() as box:
        yield box


# --- 静态：编码与语法 -----------------------------------------------------------------


def test_script_is_bom_or_pure_ascii_with_lf_endings() -> None:
    """无 BOM 时 5.1 按系统 ANSI 代码页解码：纯 ASCII 才能保证解码结果逐字节不变。

    V039-R1-001 的根因正是「无 BOM + 非 ASCII」把中文注释与下一行合并。
    """
    raw = SCRIPT_PATH.read_bytes()
    has_bom = raw.startswith(b"\xef\xbb\xbf")
    non_ascii = [index for index, byte in enumerate(raw) if byte > 0x7F]

    assert has_bom or non_ascii == [], (
        f"build-android.ps1 既无 BOM 又含非 ASCII 字节（偏移 {non_ascii[:8]}）："
        "PowerShell 5.1 会按 ANSI 代码页解码"
    )
    assert b"\r" not in raw, "脚本含 CR 行尾；.gitattributes 约定 LF"


def test_script_parses_under_powershell_51() -> None:
    """用 PowerShell 5.1 自己的解析器读真实文件：0 语法错误。"""
    script = (
        "$tokens = $null; $errors = $null\n"
        f"$ast = [System.Management.Automation.Language.Parser]::ParseFile('{SCRIPT_PATH}', [ref]$tokens, [ref]$errors)\n"
        "Write-Output ('errors=' + @($errors).Count)\n"
        "foreach ($e in @($errors)) { Write-Output ('ERR ' + $e.Message) }\n"
    )
    result = subprocess.run(
        [_require_powershell(), "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", script],
        capture_output=True,
        text=False,
        encoding=_ps_output_encoding(),
        errors="replace",
        timeout=120.0,
    )

    assert result.returncode == 0, result.stderr
    assert result.stdout.splitlines()[0].strip() == "errors=0", result.stdout


# --- dry-run：tauri.properties 必须在 gradle 之前写好 -----------------------------------


def test_dry_run_writes_tauri_properties_before_gradle(sandbox: _AndroidBuildSandbox) -> None:
    """整条脚本在沙箱里跑通，属性文件落在 gradle 读取的位置且先于打包写出。"""
    result = sandbox.run()

    assert result.returncode == 0, result.stdout + result.stderr
    assert sandbox.recorded_calls() == ["npm", "cargo", "gradlew"], sandbox.recorded_calls()
    assert sandbox.properties.exists(), "脚本没有生成 gen/android/app/tauri.properties"

    properties = _properties_lines(sandbox.properties)
    assert properties["tauri.android.versionName"] == sandbox.app_version
    assert int(properties["tauri.android.versionCode"]) == _version_code(sandbox.app_version)
    assert int(properties["tauri.android.versionCode"]) > DEVICE_VERSION_CODE, (
        "真机现存包 versionCode=3007，本次次产物必须更大，否则 adb install -r 仍报降级"
    )

    assert sandbox.properties_at_gradle_time.exists(), "gradle 打包时 tauri.properties 还不存在"
    assert sandbox.properties_at_gradle_time.read_text(encoding="ascii") == sandbox.properties.read_text(
        encoding="ascii"
    )
    assert f"versionCode={_version_code(sandbox.app_version)}" in result.stdout


@pytest.mark.parametrize(
    ("version", "expected_code"),
    [
        ("1.2.3", 1002003),
        # 仓库真实出现过的带后缀版本（semver 预发布标识）：versionName 原样保留。
        ("0.3.2-patch1", 3002),
    ],
)
def test_version_code_follows_the_tauri_cli_scheme(version: str, expected_code: int) -> None:
    """major * 1000000 + minor * 1000 + patch：与 tauri CLI 生成的值保持同一口径。"""
    with _sandbox(version) as box:
        result = box.run()

        assert result.returncode == 0, result.stdout + result.stderr
        properties = _properties_lines(box.properties)
    assert properties == {
        "tauri.android.versionName": version,
        "tauri.android.versionCode": str(expected_code),
    }


@pytest.mark.parametrize("version", [None, "0.0.0", "0.3", "not-a-version"])
def test_unusable_version_fails_loudly_without_packaging(version: str | None) -> None:
    """版本缺失或无法派生合法 versionCode 时必须非零退出，且不调用 gradle 打包。"""
    with _sandbox(version) as box:
        result = box.run()

        calls = box.recorded_calls()
    assert result.returncode != 0, f"版本 '{version}' 未被拒绝：{result.stdout}"
    assert "gradlew" not in calls, f"版本非法却已经开始打包：{calls}"
    assert "version" in result.stderr.lower(), result.stderr


def test_generated_properties_match_the_real_gradle_consumer() -> None:
    """键名与位置以真实 gradle 工程为准：`app/build.gradle.kts` 读的就是这两个键。

    `gen/android/` 是 git 忽略的本机构建产物（CI 上不存在），缺失时跳过，
    上面的 dry-run 仍然覆盖脚本自身的生成行为。
    """
    if not GRADLE_APP_BUILD.exists():
        pytest.skip("本机没有 gen/android 工程（git 忽略的构建产物），跳过消费方一致性核对")

    text = GRADLE_APP_BUILD.read_text(encoding="utf-8")
    assert 'file("tauri.properties")' in text
    assert 'tauriProperties.getProperty("tauri.android.versionCode", "1")' in text
    assert 'tauriProperties.getProperty("tauri.android.versionName", "1.0")' in text
